DROP TABLE IF EXISTS WORK;

CREATE TABLE WORK(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
PROJECT VARCHAR(100) NOT NULL,
START_TIME VARCHAR(10) NOT NULL,
END_TIME VARCHAR(10) NOT NULL,
EMPLOYEE_ID BIGINT NOT NULL,
);
